import { NextPage } from 'next';
import Head from 'next/head';
import { Card } from 'react-bootstrap';

import My_Navbar from '../Navbar';

const Artifact: NextPage = () => {

  return (
    <>
      <Head>
        <title> แนะนำสิ่งประดิษฐ์จากขวดพลาสติก - โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {My_Navbar("artifact")}

      <Card>
        <Card.Header> สิ่งประดิษฐ์จากขวดพลาสติก </Card.Header>
        <Card.Body>
          <Card.Title> (แนะนำ) สิ่งประดิษฐ์จากขวดพลาสติก ที่น่าสนใจ </Card.Title>
          <Card.Text>
          https://www.trueplookpanya.com/knowledge/content/69429/-diyhom-diy-
          </Card.Text>
        </Card.Body>
      </Card>
    </>
  )
}

export default Artifact