import { NextPage } from 'next';
import Head from 'next/head';
import Script from 'next/script';
import { Card } from 'react-bootstrap';
import My_Navbar from '../Navbar';

const ProjectBook: NextPage = () => {

  return (
    <>
      <Head>
        <title> รูปเล่ม - โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {My_Navbar("project_book")}

      <Card>
        <Card.Header> รูปเล่มโครงการ </Card.Header>
        <Card.Body>
          <div id="adobe-dc-view"></div>
          <Script src="https://documentcloud.adobe.com/view-sdk/main.js" />
          <Script id="show-pdf">
            {`
            document.addEventListener("adobe_dc_view_sdk.ready", function(){ 
              var adobeDCView = new AdobeDC.View({clientId: "ccacdb747cb1437ba8b41572633d54b6", divId: "adobe-dc-view"});
              adobeDCView.previewFile({
                content:{location: {url: "/zaza.pdf"}},
                metaData:{fileName: "zaza.pdf"}
              }, {});
            });
            `}
          </Script>
        </Card.Body>
      </Card>
    </>
  )
}

export default ProjectBook

