import { NextPage } from 'next';
import Head from 'next/head';
import { Card, Image as BsImage, Accordion } from 'react-bootstrap';
import My_Navbar from '../Navbar';

const ProjectBook: NextPage = () => {

  return (
    <>
      <Head>
        <title> รูปเล่ม - โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {My_Navbar("project_book")}

      <Card>
        <Card.Header> รูปเล่มโครงการ </Card.Header>
        <Card.Body>

          <Accordion>
            <Accordion.Item eventKey="0">
              <Accordion.Header> รูปเล่มโครงการ (ฉบับย่อ) </Accordion.Header>
              <Accordion.Body>
                <BsImage src="/project_book/แบบฟอร์มฉบับย่อ โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก_Page_1.jpg" fluid />
                <BsImage src="/project_book/แบบฟอร์มฉบับย่อ โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก_Page_2.jpg" fluid />
                <BsImage src="/project_book/แบบฟอร์มฉบับย่อ โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก_Page_3.jpg" fluid />
              </Accordion.Body>
            </Accordion.Item>

            <Accordion.Item eventKey="1">
              <Accordion.Header> พาวเวอร์พ้อย นำเสนอโครงการ </Accordion.Header>
              <Accordion.Body>
                <BsImage src="/project_book/แบบฟอร์มฉบับย่อ โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก_Page_1.jpg" fluid />
                <BsImage src="/project_book/แบบฟอร์มฉบับย่อ โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก_Page_2.jpg" fluid />
                <BsImage src="/project_book/แบบฟอร์มฉบับย่อ โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก_Page_3.jpg" fluid />
              </Accordion.Body>
            </Accordion.Item>
          </Accordion>

        </Card.Body>
      </Card>
    </>
  )
}

export default ProjectBook

