import { NextPage } from 'next';
import Head from 'next/head';
import { Card } from 'react-bootstrap';

import My_Navbar from '../Navbar';

const SeparateBottles: NextPage = () => {

  return (
    <>
      <Head>
        <title> แนะนำวิธีแยกขวด - โครงการรณรงค์ปลูกจิตสำนึก งดทิ้งขวดพลาสติก </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {My_Navbar("separate_bottles")}

      <Card>
        <Card.Header> วิธีแยกพลาสติก </Card.Header>
        <Card.Body>
          <Card.Title> วิธีแยกพลาสติกขายง่าย ๆ สร้างรายได้ </Card.Title>
          <Card.Text>
            https://hilight.kapook.com/view/203772
            <br/>
            https://hilight.kapook.com/view/192733
          </Card.Text>
        </Card.Body>
      </Card>
    </>
  )
}

export default SeparateBottles